# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
relative_permalinks: true

# Setup
title:               GT Agency
tagline:             'We Create the Agents'
description:         "The Automated Intelligence Club at the Georgia Tech College of Computing"
url:                 http://gtagency.github.io
baseurl:             ''
paginate:            5

# About/contact
author:
  name:              George Burdell

# Custom vars
version:             1.0.0
github_url: https://github.com/gtagency

markdown: redcarpet

gems:
  - jekyll-mentions
